### ISSUE TITLE
Missing go.sum entry

### ISSUE THREAD

**Issue by ableocardo** [gagliardetto/codebox#1]
Hello,

I am new to go and trying to run codebox on https://github.com/argoproj-labs/argocd-operator. I downloaded the package using go get and was able to build it.

The command codebox --out-dir=./generated/compressed --pkg=net/http --stub --http works

But when I try the command : codebox --out-dir=./generated/compressed --pkg=github.com/argoproj-labs/argocd-operator --stub --http . I get the error

[INFO][0|13:04:17|428ms] Using latest &{"v0.0.15" "2021-04-20 15:27:58 +0000 UTC" "" ""} version
&modfetch.RevInfo{
    Version: "v0.0.15",
    Time:    time.Time{
        wall: 0x0,
        ext:  63754529278,
        loc:  (*time.Location)(nil),
    },
    Name:  "",
    Short: "",
}
/var/folders/kb/s1y50h751hd1jwt8zdk_4sv00000gn/T/codebox240782925
[INFO][1|13:04:17|432ms] Using the following temporary go.mod file:

module example.com/hello/world

require github.com/argoproj-labs/argocd-operator v0.0.15 // indirect

[INFO][2|13:04:17|432ms] Starting to load package "github.com/argoproj-labs/argocd-operator/cmd/manager" ...
panic: error scanning package "github.com/argoproj-labs/argocd-operator/cmd/manager": error while scanPackageWithScanner: error while packages.Load: err: exit status 1: stderr: go: github.com/argoproj-labs/argocd-operator@v0.0.15: missing go.sum entry; to add it:
	go mod download github.com/argoproj-labs/argocd-operator

Any pointers on what could be going wrong would be really helpful.

**Comment by gagliardetto** [comment]
Hi @ableocardo 

- github.com/argoproj-labs/argocd-operator does not seem to be a package itself (you to specify specific packages just like you would import them; https://pkg.go.dev/github.com/argoproj-labs/argocd-operator does not contain actual source elements and cannot be used by codebox).
- Maybe try `codebox --out-dir=./generated/compressed --pkg=github.com/argoproj-labs/argocd-operator/pkg/apis/argoproj/v1alpha1@v0.0.15 --stub --http`
- Which Go version have you built it with? `codebox` doesn't support >=go1.16: use go1.15.3 and compile codebox with it.


For more advanced modelling, you should use https://github.com/gagliardetto/codemill

Example: `codemill -spec=argoproj.json -dir=generated -http=true -gen=false`

and `argoproj.json` should be

```json
{
    "Name": "Argoproj",
    "Preload": ["github.com/argoproj-labs/argocd-operator/pkg/apis/argoproj/v1alpha1@v0.0.15"],
    "Models": []
}
```

**Comment by ableocardo** [comment]
Hello @gagliardetto,

Thank You ! very much for the pointer and I downgraded my Go. Now, code box and codemill were able to run. But if I run it on any other package in the operator. It throws : 

[INFO][0|12:32:01|229ms] Using latest &{"v4.5.1+incompatible" "2020-11-10 14:15:46 +0000 UTC" "" ""} version
&modfetch.RevInfo{
    Version: "v4.5.1+incompatible",
    Time:    time.Time{
        wall: 0x0,
        ext:  63740614546,
        loc:  (*time.Location)(nil),
    },
    Name:  "",
    Short: "",
}
/tmp/codebox336911171
[INFO][1|12:32:01|230ms] Using the following temporary go.mod file:

module example.com/hello/world

require github.com/crunchydata/postgres-operator v4.5.1+incompatible // indirect

[INFO][2|12:32:01|230ms] Starting to load package "github.com/crunchydata/postgres-operator/internal/logging" ...
[INFO][3|12:32:01|839ms] Loaded package "github.com/crunchydata/postgres-operator/internal/logging"
panic: error scanning package "github.com/crunchydata/postgres-operator/internal/logging": error while scanPackageWithScanner: error while packages.Load: The following errors occurred:
 -  /home/XXXX/go/pkg/mod/github.com/crunchydata/postgres-operator@v4.5.1+incompatible/internal/config/pgoconfig.go:36:2: module k8s.io/client-go@latest found (v1.5.2), but does not contain package k8s.io/client-go/kubernetes
 -  /home/XXXX/go/pkg/mod/github.com/crunchydata/postgres-operator@v4.5.1+incompatible/internal/config/pgoconfig.go:36:2: could not import k8s.io/client-go/kubernetes (invalid package name: "")

goroutine 1 [running]:
main.main()
	/home/XXXX/go/src/codebox/main.go:65 +0x2cfa

**Comment by gagliardetto** [comment]
As far as I can see, all versions of github.com/crunchydata/postgres-operator are `incompatible`: https://pkg.go.dev/github.com/crunchydata/postgres-operator?tab=versions

https://stackoverflow.com/questions/57355929/what-does-incompatible-in-go-mod-mean-will-it-cause-harm

You could try to fork the repo and fix it.
